[build]
builder = "nixpacks"

[build.nixpacks]
providers = ["node"]

[deploy]
buildCommand = "npm install && npm run build"
startCommand = "npx serve -s build -l $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100